/**
 * Helper to load the sidebar JSON only if it exists
 * returns empty array otherwise
 */
 function loadSidebarIfExists() {
    try {
        return require("./docs/api/sidebar.json")
    } catch {
        return []
    }
}

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    docSidebar: [{ type: 'autogenerated', dirName: 'docs' }],
    apiSidebar: loadSidebarIfExists()
};

module.exports = sidebars;