name: Test deployment

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '42 14 * * 3' # every thursday at 2:42 pm

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew build dokkaHtmlMultiModule
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
          cache-dependency-path: website/package-lock.json
      - name: Modify Dokka output
        uses: nk-coding/dokka-html-mdx-transform@1_7_10
        with:
          src: "build/dokka/htmlMultiModule"
          modules: |
            graphglue-core
            graphglue
          dest: "website/docs"
          folder: "api"
      - name: Install dependencies
        run: npm ci
        working-directory: website
      - name: Build website
        run: npm run build
        working-directory: website