name: Test deployment

on:
  pull_request:
    branches:
      - main

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Execute Gradle build
        run: ./gradlew build dokkaHtmlMultiModule
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: website/package-lock.json
      - name: Modify Dokka output
        uses: graphglue/dokka-html-mdx-transform@v1.7.20
        with:
          src: "build/dokka/htmlMultiModule"
          modules: |
            graphglue-core
            graphglue
          dest: "website/docs"
          folder: "api"
      - name: Install dependencies
        run: npm ci
        working-directory: website
      - name: Build website
        run: npm run build
        working-directory: website